### ISSUE TITLE
Math Magicians: refactor with hooks

### ISSUE THREAD

**Issue by kensteph** [kensteph/math-magicians#4]
Hi there 👋!
I already use functional components and hooks in my project.

### Functional Components
Functional components are a type of component in React that are defined as functions rather than classes. They are often used for simpler components that don't require complex state management or lifecycle methods.

### Use of Functional Component
To use a functional component, you first define the component as a function that takes in props (short for properties, which are used to pass data to the component) as an argument. Within the function, you can then return the JSX (JavaScript XML) that defines the component's UI.
Here is an example : 

```jsx 
    const Button= ( { symbol} ) => {
         return <h1> {symbole} </h1>
}
```

### Hooks
Hooks are functions that let you use React features like state and lifecycle methods in functional components. You can create also your own hook by pretending the name of the function by 'use' (Ex: useDisplayUser).
One of the most used hooks is useState. This hook helps you manage your application states.

### Use of useState
Call useState at the top level of your component to declare a state variable. This function returns an array with 2 items. The first item is the state variable and the second is a function that lets you update the state to a different value and trigger a re-render.

Here is an example : 

```jsx
const Calculator= () => {
  const [result, setResult] = useState(0);
  return (
    <div>
      <p>{result.total}</p>
      <Button symbole= "AC"/>
        ...
    </div>
  );
}
```

Thank you,

**Comment by omarsalem7** [comment]
Hi @kensteph 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete! :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Good description of the functional component
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kensteph** [comment]
Thank you @omarsalem7.
